//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
//         Any modifications to this file will be lost upon recompilation of the source schema.
//         Generated on: 2019.08.16 at 01:27:54 PM EEST
//


package com.ted.eBayDIT.xmlParser;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected         content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Item" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="Currently" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Buy_Price" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="First_Bid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Number_of_Bids" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="Bids"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Bid" maxOccurs="unbounded" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="Bidder"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                                 &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                               &lt;/sequence&gt;
 *                                               &lt;attribute name="Rating" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                                               &lt;attribute name="UserID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                       &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Location"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *                           &lt;attribute name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Started" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Ends" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Seller"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="Rating" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                           &lt;attribute name="UserID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="ItemID" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "item"
})
@XmlRootElement(name = "Items")
public class Items {
    @Override
    public String toString() {
        return "Items{" +
                "item=" + item +
                '}';
    }

    @XmlElement(name = "Item")
    protected List<Items.Item> item;

    /**
     * Gets the value of the item property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Items.Item }
     *
     *
     */
    public List<Items.Item> getItem() {
        if (item == null) {
            item = new ArrayList<Items.Item>();
        }
        return this.item;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected         content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="Currently" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Buy_Price" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="First_Bid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Number_of_Bids" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
     *         &lt;element name="Bids"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Bid" maxOccurs="unbounded" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Bidder"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                                       &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                                     &lt;/sequence&gt;
     *                                     &lt;attribute name="Rating" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *                                     &lt;attribute name="UserID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                             &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Location"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
     *                 &lt;attribute name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Started" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Ends" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Seller"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="Rating" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *                 &lt;attribute name="UserID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="ItemID" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "category",
        "currently",
        "buyPrice",
        "firstBid",
        "numberOfBids",
        "bids",
        "location",
        "country",
        "started",
        "ends",
        "seller",
        "description"
    })
    public static class Item {

        @Override
        public String toString() {
            return "Item{" +
                    "name='" + name + '\'' +
                    ", category=" + category +
                    ", currently='" + currently + '\'' +
                    ", buyPrice='" + buyPrice + '\'' +
                    ", firstBid='" + firstBid + '\'' +
                    ", numberOfBids=" + numberOfBids +
                    ", bids=" + bids +
                    ", location=" + location +
                    ", country='" + country + '\'' +
                    ", started='" + started + '\'' +
                    ", ends='" + ends + '\'' +
                    ", seller=" + seller +
                    ", description='" + description + '\'' +
                    ", itemID=" + itemID +
                    '}';
        }

        @XmlElement(name = "Name", required = true)
        protected String name;
        @XmlElement(name = "Category")
        protected List<String> category;
        @XmlElement(name = "Currently", required = true)
        protected String currently;
        @XmlElement(name = "Buy_Price")
        protected String buyPrice;
        @XmlElement(name = "First_Bid", required = true)
        protected String firstBid;
        @XmlElement(name = "Number_of_Bids")
        protected byte numberOfBids;
        @XmlElement(name = "Bids", required = true)
        protected Items.Item.Bids bids;
        @XmlElement(name = "Location", required = true)
        protected Items.Item.Location location;
        @XmlElement(name = "Country", required = true)
        protected String country;
        @XmlElement(name = "Started", required = true)
        protected String started;
        @XmlElement(name = "Ends", required = true)
        protected String ends;
        @XmlElement(name = "Seller", required = true)
        protected Items.Item.Seller seller;
        @XmlElement(name = "Description", required = true)
        protected String description;
        @XmlAttribute(name = "ItemID")
        protected Integer itemID;

        /**
         * Gets the value of the name property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the category property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the category property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCategory().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         *
         *
         */
        public List<String> getCategory() {
            if (category == null) {
                category = new ArrayList<String>();
            }
            return this.category;
        }

        /**
         * Gets the value of the currently property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCurrently() {
            return currently;
        }

        /**
         * Sets the value of the currently property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCurrently(String value) {
            this.currently = value;
        }

        /**
         * Gets the value of the buyPrice property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getBuyPrice() {
            return buyPrice;
        }

        /**
         * Sets the value of the buyPrice property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setBuyPrice(String value) {
            this.buyPrice = value;
        }

        /**
         * Gets the value of the firstBid property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getFirstBid() {
            return firstBid;
        }

        /**
         * Sets the value of the firstBid property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setFirstBid(String value) {
            this.firstBid = value;
        }

        /**
         * Gets the value of the numberOfBids property.
         *
         */
        public byte getNumberOfBids() {
            return numberOfBids;
        }

        /**
         * Sets the value of the numberOfBids property.
         *
         */
        public void setNumberOfBids(byte value) {
            this.numberOfBids = value;
        }

        /**
         * Gets the value of the bids property.
         *
         * @return
         *     possible object is
         *     {@link Items.Item.Bids }
         *
         */
        public Items.Item.Bids getBids() {
            return bids;
        }

        /**
         * Sets the value of the bids property.
         *
         * @param value
         *     allowed object is
         *     {@link Items.Item.Bids }
         *
         */
        public void setBids(Items.Item.Bids value) {
            this.bids = value;
        }

        /**
         * Gets the value of the location property.
         *
         * @return
         *     possible object is
         *     {@link Items.Item.Location }
         *
         */
        public Items.Item.Location getLocation() {
            return location;
        }

        /**
         * Sets the value of the location property.
         *
         * @param value
         *     allowed object is
         *     {@link Items.Item.Location }
         *
         */
        public void setLocation(Items.Item.Location value) {
            this.location = value;
        }

        /**
         * Gets the value of the country property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCountry(String value) {
            this.country = value;
        }

        /**
         * Gets the value of the started property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getStarted() {
            return started;
        }

        /**
         * Sets the value of the started property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setStarted(String value) {
            this.started = value;
        }

        /**
         * Gets the value of the ends property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getEnds() {
            return ends;
        }

        /**
         * Sets the value of the ends property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setEnds(String value) {
            this.ends = value;
        }

        /**
         * Gets the value of the seller property.
         *
         * @return
         *     possible object is
         *     {@link Items.Item.Seller }
         *
         */
        public Items.Item.Seller getSeller() {
            return seller;
        }

        /**
         * Sets the value of the seller property.
         *
         * @param value
         *     allowed object is
         *     {@link Items.Item.Seller }
         *
         */
        public void setSeller(Items.Item.Seller value) {
            this.seller = value;
        }

        /**
         * Gets the value of the description property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the itemID property.
         *
         * @return
         *     possible object is
         *     {@link Integer }
         *
         */
        public Integer getItemID() {
            return itemID;
        }

        /**
         * Sets the value of the itemID property.
         *
         * @param value
         *     allowed object is
         *     {@link Integer }
         *
         */
        public void setItemID(Integer value) {
            this.itemID = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected         content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Bid" maxOccurs="unbounded" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Bidder"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                             &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                           &lt;/sequence&gt;
         *                           &lt;attribute name="Rating" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
         *                           &lt;attribute name="UserID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                   &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class Bids {

            @XmlElementRef(name = "Bid", type = JAXBElement.class, required = false)
            @XmlMixed
            protected List<Serializable> content;

            /**
             * Gets the value of the content property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link Items.Item.Bids.Bid }{@code >}
             * {@link String }
             *
             *
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected         content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Bidder"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *                   &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *                 &lt;/sequence&gt;
             *                 &lt;attribute name="Rating" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
             *                 &lt;attribute name="UserID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *         &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "bidder",
                "time",
                "amount"
            })
            public static class Bid {

                @XmlElement(name = "Bidder", required = true)
                protected Items.Item.Bids.Bid.Bidder bidder;
                @XmlElement(name = "Time", required = true)
                protected String time;
                @XmlElement(name = "Amount", required = true)
                protected String amount;

                /**
                 * Gets the value of the bidder property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Items.Item.Bids.Bid.Bidder }
                 *
                 */
                public Items.Item.Bids.Bid.Bidder getBidder() {
                    return bidder;
                }

                /**
                 * Sets the value of the bidder property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Items.Item.Bids.Bid.Bidder }
                 *
                 */
                public void setBidder(Items.Item.Bids.Bid.Bidder value) {
                    this.bidder = value;
                }

                /**
                 * Gets the value of the time property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getTime() {
                    return time;
                }

                /**
                 * Sets the value of the time property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setTime(String value) {
                    this.time = value;
                }

                /**
                 * Gets the value of the amount property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getAmount() {
                    return amount;
                }

                /**
                 * Sets the value of the amount property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setAmount(String value) {
                    this.amount = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected         content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
                 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
                 *       &lt;/sequence&gt;
                 *       &lt;attribute name="Rating" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
                 *       &lt;attribute name="UserID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "content"
                })
                public static class Bidder {

                    @XmlElementRefs({
                        @XmlElementRef(name = "Location", type = JAXBElement.class, required = false),
                        @XmlElementRef(name = "Country", type = JAXBElement.class, required = false)
                    })
                    @XmlMixed
                    protected List<Serializable> content;
                    @XmlAttribute(name = "Rating")
                    protected Short rating;
                    @XmlAttribute(name = "UserID")
                    protected String userID;

                    /**
                     * Gets the value of the content property.
                     *
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the content property.
                     *
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getContent().add(newItem);
                     * </pre>
                     *
                     *
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link JAXBElement }{@code <}{@link String }{@code >}
                     * {@link JAXBElement }{@code <}{@link String }{@code >}
                     * {@link String }
                     *
                     *
                     */
                    public List<Serializable> getContent() {
                        if (content == null) {
                            content = new ArrayList<Serializable>();
                        }
                        return this.content;
                    }

                    /**
                     * Gets the value of the rating property.
                     *
                     * @return
                     *     possible object is
                     *     {@link Short }
                     *
                     */
                    public Short getRating() {
                        return rating;
                    }

                    /**
                     * Sets the value of the rating property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link Short }
                     *
                     */
                    public void setRating(Short value) {
                        this.rating = value;
                    }

                    /**
                     * Gets the value of the userID property.
                     *
                     * @return
                     *     possible object is
                     *     {@link String }
                     *
                     */
                    public String getUserID() {
                        return userID;
                    }

                    /**
                     * Sets the value of the userID property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *
                     */
                    public void setUserID(String value) {
                        this.userID = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected         content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
         *       &lt;attribute name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Location {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "Latitude")
            protected Float latitude;
            @XmlAttribute(name = "Longitude")
            protected Float longitude;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the latitude property.
             *
             * @return
             *     possible object is
             *     {@link Float }
             *
             */
            public Float getLatitude() {
                return latitude;
            }

            /**
             * Sets the value of the latitude property.
             *
             * @param value
             *     allowed object is
             *     {@link Float }
             *
             */
            public void setLatitude(Float value) {
                this.latitude = value;
            }

            /**
             * Gets the value of the longitude property.
             *
             * @return
             *     possible object is
             *     {@link Float }
             *
             */
            public Float getLongitude() {
                return longitude;
            }

            /**
             * Sets the value of the longitude property.
             *
             * @param value
             *     allowed object is
             *     {@link Float }
             *
             */
            public void setLongitude(Float value) {
                this.longitude = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected         content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="Rating" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
         *       &lt;attribute name="UserID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Seller {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "Rating")
            protected Short rating;
            @XmlAttribute(name = "UserID")
            protected String userID;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the rating property.
             *
             * @return
             *     possible object is
             *     {@link Short }
             *
             */
            public Short getRating() {
                return rating;
            }

            /**
             * Sets the value of the rating property.
             *
             * @param value
             *     allowed object is
             *     {@link Short }
             *
             */
            public void setRating(Short value) {
                this.rating = value;
            }

            /**
             * Gets the value of the userID property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getUserID() {
                return userID;
            }

            /**
             * Sets the value of the userID property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setUserID(String value) {
                this.userID = value;
            }

        }

    }

}
