//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
//         Any modifications to this file will be lost upon recompilation of the source schema.
//         Generated on: 2019.08.16 at 01:27:54 PM EEST
//


package com.ted.eBayDIT.xmlParser;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.mypackage package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ItemsItemBidsBid_QNAME = new QName("", "Bid");
    private final static QName _ItemsItemBidsBidBidderLocation_QNAME = new QName("", "Location");
    private final static QName _ItemsItemBidsBidBidderCountry_QNAME = new QName("", "Country");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mypackage
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Items }
     *
     */
    public Items createItems() {
        return new Items();
    }

    /**
     * Create an instance of {@link Items.Item }
     *
     */
    public Items.Item createItemsItem() {
        return new Items.Item();
    }

    /**
     * Create an instance of {@link Items.Item.Bids }
     *
     */
    public Items.Item.Bids createItemsItemBids() {
        return new Items.Item.Bids();
    }

    /**
     * Create an instance of {@link Items.Item.Bids.Bid }
     *
     */
    public Items.Item.Bids.Bid createItemsItemBidsBid() {
        return new Items.Item.Bids.Bid();
    }

    /**
     * Create an instance of {@link Items.Item.Location }
     *
     */
    public Items.Item.Location createItemsItemLocation() {
        return new Items.Item.Location();
    }

    /**
     * Create an instance of {@link Items.Item.Seller }
     *
     */
    public Items.Item.Seller createItemsItemSeller() {
        return new Items.Item.Seller();
    }

    /**
     * Create an instance of {@link Items.Item.Bids.Bid.Bidder }
     *
     */
    public Items.Item.Bids.Bid.Bidder createItemsItemBidsBidBidder() {
        return new Items.Item.Bids.Bid.Bidder();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Items.Item.Bids.Bid }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Items.Item.Bids.Bid }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Bid", scope = Items.Item.Bids.class)
    public JAXBElement<Items.Item.Bids.Bid> createItemsItemBidsBid(Items.Item.Bids.Bid value) {
        return new JAXBElement<Items.Item.Bids.Bid>(_ItemsItemBidsBid_QNAME, Items.Item.Bids.Bid.class, Items.Item.Bids.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Location", scope = Items.Item.Bids.Bid.Bidder.class)
    public JAXBElement<String> createItemsItemBidsBidBidderLocation(String value) {
        return new JAXBElement<String>(_ItemsItemBidsBidBidderLocation_QNAME, String.class, Items.Item.Bids.Bid.Bidder.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Country", scope = Items.Item.Bids.Bid.Bidder.class)
    public JAXBElement<String> createItemsItemBidsBidBidderCountry(String value) {
        return new JAXBElement<String>(_ItemsItemBidsBidBidderCountry_QNAME, String.class, Items.Item.Bids.Bid.Bidder.class, value);
    }

}
